### ISSUE TITLE
Условия внутри обработки исключений

### ISSUE THREAD

**Issue by tolcheev** [AAstahckin/qa_guru_19_api#9]
https://github.com/AAstahckin/qa_guru_19_api/blob/1379e14557282d8f1a8a60db4ede629fc30cc778/src/test/java/api/utils/DateTimeCheck.java#L24

Стоит избегать if внутри try..catch блока, тем более одного...

**Comment by AAstahckin** [comment]
done: https://github.com/AAstahckin/qa_guru_19_api/blob/master/src/test/java/api/utils/DateTimeCheck.java#L22
